[request_definition]
r = sub, dom, act, node_type, transition

[policy_definition]
p = sub, dom, act, node_type, transition

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.dom == p.dom && r.act == p.act && (p.node_type == "*" || r.node_type == p.node_type) && (p.transition == "*" || r.transition == p.transition)
