@echo off
setlocal EnableDelayedExpansion
title PLM Core Dev

echo [run.bat] PLM Core - Dev script with hot rebuild
echo [run.bat] Usage: run.bat [--build]
echo.

REM ────────────────────────────────────────────────────────────
REM Optional full rebuild
REM ────────────────────────────────────────────────────────────
if /i "%1"=="--build" (
    echo [run.bat] Full rebuild...
    docker compose build --no-cache
    if errorlevel 1 ( echo [run.bat] ERROR: build failed. & pause & exit /b 1 )
)

REM ────────────────────────────────────────────────────────────
REM Start services
REM ────────────────────────────────────────────────────────────
echo [run.bat] Starting services...
docker compose up -d
if errorlevel 1 ( echo [run.bat] ERROR: docker compose up failed. & pause & exit /b 1 )

echo.
echo   Frontend : http://localhost:3000
echo   API      : http://localhost:8080/api
echo.

REM Open browser (best-effort)
start "" "http://localhost:3000"

REM Tail logs in a separate window — close that window to stop log tailing
start "PLM Logs" cmd /k "docker compose logs -f"

REM ────────────────────────────────────────────────────────────
REM Write PowerShell watch script to a temp file
REM Uses System.IO.FileSystemWatcher (built-in, no extra install needed)
REM Requires PowerShell 5.1+ (present on Windows 10/11 by default)
REM ────────────────────────────────────────────────────────────
set "PS=%TEMP%\plm_watch_%RANDOM%.ps1"
del /f "%PS%" 2>nul

echo # PLM Core file watcher - generated by run.bat >> "%PS%"
echo $global:queue = [System.Collections.Queue]::Synchronized([System.Collections.Queue]::new()) >> "%PS%"
echo $debounce = @{ backend = [datetime]::MinValue; frontend = [datetime]::MinValue } >> "%PS%"
echo. >> "%PS%"
echo function Add-Watcher($path, $tag, $recurse) { >> "%PS%"
echo   if (-not (Test-Path $path)) { >> "%PS%"
echo     Write-Host "[run.bat] WARNING: path not found, skipping: $path" -ForegroundColor Yellow >> "%PS%"
echo     return >> "%PS%"
echo   } >> "%PS%"
echo   $w = New-Object System.IO.FileSystemWatcher >> "%PS%"
echo   $w.Path = (Resolve-Path $path).Path >> "%PS%"
echo   $w.IncludeSubdirectories = $recurse >> "%PS%"
echo   $w.EnableRaisingEvents   = $true >> "%PS%"
echo   $a = [scriptblock]::Create("`$global:queue.Enqueue('$tag')") >> "%PS%"
echo   Register-ObjectEvent $w 'Changed' -Action $a ^| Out-Null >> "%PS%"
echo   Register-ObjectEvent $w 'Created' -Action $a ^| Out-Null >> "%PS%"
echo   Register-ObjectEvent $w 'Deleted' -Action $a ^| Out-Null >> "%PS%"
echo   Register-ObjectEvent $w 'Renamed' -Action $a ^| Out-Null >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo # Backend: src recursively + plm-api root non-recursively (pom.xml, Dockerfile) >> "%PS%"
echo Add-Watcher 'plm-api\src' 'backend'  $true >> "%PS%"
echo Add-Watcher 'plm-api'     'backend'  $false >> "%PS%"
echo # Frontend: src recursively + frontend root non-recursively (index.html, vite.config.js, ...) >> "%PS%"
echo Add-Watcher 'frontend\src' 'frontend' $true >> "%PS%"
echo Add-Watcher 'frontend'     'frontend' $false >> "%PS%"
echo. >> "%PS%"
echo Write-Host '[run.bat] Watching for changes (FileSystemWatcher)...' -ForegroundColor Cyan >> "%PS%"
echo Write-Host '[run.bat]   plm-api/  -> Docker rebuild + restart' >> "%PS%"
echo Write-Host '[run.bat]   frontend/ -> Vite build + nginx restart' >> "%PS%"
echo Write-Host '[run.bat] Press Ctrl+C to stop watching. Containers keep running.' >> "%PS%"
echo Write-Host '[run.bat] Use: docker compose down   to stop all containers.' >> "%PS%"
echo. >> "%PS%"
echo while ($true) { >> "%PS%"
echo   Start-Sleep -Milliseconds 500 >> "%PS%"
echo   if ($global:queue.Count -eq 0) { continue } >> "%PS%"
echo   $tag = $null >> "%PS%"
echo   while ($global:queue.Count -gt 0) { $tag = $global:queue.Dequeue() } >> "%PS%"
echo   if (-not $tag) { continue } >> "%PS%"
echo   $now = [datetime]::Now >> "%PS%"
echo   if (($now - $debounce[$tag]).TotalSeconds -lt 3) { continue } >> "%PS%"
echo   $debounce[$tag] = $now >> "%PS%"
echo   Write-Host "[run.bat] $tag changed - rebuilding..." -ForegroundColor Green >> "%PS%"
echo   if ($tag -eq 'frontend') { >> "%PS%"
echo     docker compose build --no-cache plm-frontend >> "%PS%"
echo     docker compose up -d --no-deps --force-recreate plm-frontend >> "%PS%"
echo     Write-Host '[run.bat] Frontend restarted.' -ForegroundColor Green >> "%PS%"
echo   } else { >> "%PS%"
echo     docker compose build --no-cache plm-backend >> "%PS%"
echo     docker compose up -d --no-deps --force-recreate plm-backend >> "%PS%"
echo     Write-Host '[run.bat] Backend container started - waiting for health check...' -ForegroundColor Yellow >> "%PS%"
echo     $ready = $false >> "%PS%"
echo     for ($i = 0; $i -lt 60; $i++) { >> "%PS%"
echo       Start-Sleep -Seconds 2 >> "%PS%"
echo       try { >> "%PS%"
echo         $r = Invoke-WebRequest -Uri 'http://localhost:8080/actuator/health' -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop >> "%PS%"
echo         if ($r.StatusCode -eq 200) { $ready = $true; break } >> "%PS%"
echo       } catch {} >> "%PS%"
echo       Write-Host '.' -NoNewline >> "%PS%"
echo     } >> "%PS%"
echo     if ($ready) { Write-Host ''; Write-Host '[run.bat] Backend ready.' -ForegroundColor Green } >> "%PS%"
echo     else { Write-Host ''; Write-Host '[run.bat] WARNING: backend did not become healthy within 120s.' -ForegroundColor Red } >> "%PS%"
echo   } >> "%PS%"
echo } >> "%PS%"

REM ────────────────────────────────────────────────────────────
REM Run the watcher — blocks until Ctrl+C
REM ────────────────────────────────────────────────────────────
echo [run.bat] Starting file watcher (PowerShell FileSystemWatcher)...
powershell -NoProfile -ExecutionPolicy Bypass -File "%PS%"

REM Reached only after Ctrl+C or PowerShell error
del /f "%PS%" 2>nul
echo.
echo [run.bat] Watcher stopped. Containers are still running.
echo [run.bat] Use: docker compose down   to stop all containers.
pause
