-- ============================================================
-- V9 — Dynamic authorization_policy schema (PR5)
-- ============================================================
--
-- Renames the existing fixed-shape authorization_policy to
-- authorization_policy_legacy and creates the shape-agnostic schema:
--
--  authorization_policy        — one row per (perm, scope, role, project_space, keys)
--  authorization_policy_key    — sidecar holding the variable key/value tuples
--
-- V10 (Java migration) backfills from the legacy table.
-- ============================================================

ALTER TABLE authorization_policy RENAME TO authorization_policy_legacy;
-- Postgres preserves index/constraint names through table rename, so each old
-- name lives on the _legacy table. Move them out of the way before creating
-- the new table (which would otherwise collide on autogenerated FK names).
ALTER TABLE authorization_policy_legacy RENAME CONSTRAINT uq_authorization_policy TO uq_authorization_policy_legacy;
ALTER TABLE authorization_policy_legacy RENAME CONSTRAINT authorization_policy_permission_code_fkey TO authorization_policy_legacy_permission_code_fkey;
ALTER TABLE authorization_policy_legacy RENAME CONSTRAINT authorization_policy_role_id_fkey         TO authorization_policy_legacy_role_id_fkey;
-- Indexes too
ALTER INDEX idx_ap_role       RENAME TO idx_ap_role_legacy;
ALTER INDEX idx_ap_scope      RENAME TO idx_ap_scope_legacy;
ALTER INDEX idx_ap_nodetype   RENAME TO idx_ap_nodetype_legacy;
ALTER INDEX idx_ap_transition RENAME TO idx_ap_transition_legacy;

CREATE TABLE authorization_policy (
    id               VARCHAR(36)  NOT NULL PRIMARY KEY,
    permission_code  VARCHAR(100) NOT NULL REFERENCES permission(permission_code),
    scope_code       VARCHAR(64)  NOT NULL REFERENCES permission_scope(scope_code),
    role_id          VARCHAR(36)  NOT NULL REFERENCES pno_role(id),
    project_space_id VARCHAR(36)  NOT NULL REFERENCES project_space(id),
    keys_fingerprint CHAR(64)     NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_authorization_policy UNIQUE (permission_code, scope_code, role_id, project_space_id, keys_fingerprint)
);

CREATE TABLE authorization_policy_key (
    policy_id  VARCHAR(36)  NOT NULL REFERENCES authorization_policy(id) ON DELETE CASCADE,
    key_name   VARCHAR(64)  NOT NULL,
    key_value  VARCHAR(255) NOT NULL,
    PRIMARY KEY (policy_id, key_name)
);

CREATE INDEX idx_apk_kv         ON authorization_policy_key (key_name, key_value);
CREATE INDEX idx_ap_role_perm   ON authorization_policy (role_id, permission_code);
CREATE INDEX idx_ap_ps_role     ON authorization_policy (project_space_id, role_id);
CREATE INDEX idx_ap_scope       ON authorization_policy (scope_code);
