[request_definition]
r = sub, project_space, scope, act, object, attrs

[policy_definition]
p = sub, project_space, scope, act, object, attrs

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.project_space == p.project_space && r.scope == p.scope && r.act == p.act && r.object == p.object && r.attrs == p.attrs
